Alert: Encountered Failure for Task "{{ task_instance.task_id }}" in DAG "{{ task_instance.dag_id }}"