[2024-11-01T18:20:37.534+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: bluebikes_data_pipeline.upload_to_gcs_task scheduled__2024-04-01T00:00:00+00:00 [queued]>
[2024-11-01T18:20:37.721+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: bluebikes_data_pipeline.upload_to_gcs_task scheduled__2024-04-01T00:00:00+00:00 [queued]>
[2024-11-01T18:20:37.754+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2024-11-01T18:20:37.882+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): upload_to_gcs_task> on 2024-04-01 00:00:00+00:00
[2024-11-01T18:20:38.050+0000] {standard_task_runner.py:57} INFO - Started process 304 to run task
[2024-11-01T18:20:38.099+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'bluebikes_data_pipeline', 'upload_to_gcs_task', 'scheduled__2024-04-01T00:00:00+00:00', '--job-id', '795', '--raw', '--subdir', 'DAGS_FOLDER/***_main.py', '--cfg-path', '/tmp/tmpvrtcp00s']
[2024-11-01T18:20:38.128+0000] {standard_task_runner.py:85} INFO - Job 795: Subtask upload_to_gcs_task
[2024-11-01T18:20:38.544+0000] {task_command.py:410} INFO - Running <TaskInstance: bluebikes_data_pipeline.upload_to_gcs_task scheduled__2024-04-01T00:00:00+00:00 [running]> on host f1ce4a924b75
[2024-11-01T18:20:42.433+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='your_name' AIRFLOW_CTX_DAG_ID='bluebikes_data_pipeline' AIRFLOW_CTX_TASK_ID='upload_to_gcs_task' AIRFLOW_CTX_EXECUTION_DATE='2024-04-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-01T00:00:00+00:00'
[2024-11-01T18:20:53.552+0000] {logging_mixin.py:150} INFO - Error uploading /opt/***/extracted_files/202404-bluebikes-tripdata.csv: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /upload/storage/v1/b/blue_bikes_bucket/o?uploadType=resumable&upload_id=AHmUCY3negfc3jZ2BR3JNkTrP8LVGnLS4E1KIZejxzl37AhXg-axWsMvuxmueQtRGbBDleB3Rb7IFSe7gbWXM8XWyOlrOAjbsbhoUHc_hmrbtlpD (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_BAD_RECORD_MAC] sslv3 alert bad record mac (_ssl.c:2570)')))
[2024-11-01T18:21:10.417+0000] {logging_mixin.py:150} INFO - Error uploading /opt/***/extracted_files/202404-bluebikes-tripdata.csv: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /upload/storage/v1/b/blue_bikes_bucket/o?uploadType=resumable&upload_id=AHmUCY0stXLbeasTNYNxFbgN2p1MzLhn1hWzB5VYyjHqSVuDOe5und7tDA3uQn1hs6inuAcDapkwt5N63lABPu-mkAGb5WPEGDy6sFVahziavpuS (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_BAD_RECORD_MAC] sslv3 alert bad record mac (_ssl.c:2570)')))
[2024-11-01T18:21:21.586+0000] {logging_mixin.py:150} INFO - Error uploading /opt/***/extracted_files/202404-bluebikes-tripdata.csv: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /upload/storage/v1/b/blue_bikes_bucket/o?uploadType=resumable&upload_id=AHmUCY1YzSH3orHgq8IobGJqVF7Q_WQD3yS3wQ5Ubk-ZzlLlA8UsWA6so5l1iia0fAF-Z7uJ3SnBIpOo18ttbFhUX5O2DSHe8udqvT0zbvj5llhHwQ (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_BAD_RECORD_MAC] sslv3 alert bad record mac (_ssl.c:2570)')))
[2024-11-01T18:22:06.176+0000] {logging_mixin.py:150} INFO - Error uploading /opt/***/extracted_files/202404-bluebikes-tripdata.csv: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /upload/storage/v1/b/blue_bikes_bucket/o?uploadType=resumable&upload_id=AHmUCY1D0Pcgq0NCV1CNzO_JTPPCU-m8EzLPUbp3s6ChXZkKqaFNMT1D6Q3WgMJWMqYqUrzpNcwn0gsnq5ljcpE2XnRrcB2ifO-4GUeJHbQByd0G (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_BAD_RECORD_MAC] sslv3 alert bad record mac (_ssl.c:2570)')))
[2024-11-01T18:24:16.295+0000] {logging_mixin.py:150} INFO - Error uploading /opt/***/extracted_files/202404-bluebikes-tripdata.csv: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /upload/storage/v1/b/blue_bikes_bucket/o?uploadType=resumable&upload_id=AHmUCY0Jw0AynFv_3cloPVcPHFBEMoVC9ddT7Q4Y2a1BE4UlkUUewCFIGA09AROoM5-bZqunr7rse2ASkFVi3QV0DCjAx0v8Tls1ZdT-Ej7WnlblzQ (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_BAD_RECORD_MAC] sslv3 alert bad record mac (_ssl.c:2570)')))
[2024-11-01T18:24:30.330+0000] {local_task_job_runner.py:225} INFO - Task exited with return code Negsignal.SIGKILL
[2024-11-01T18:24:32.923+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
